/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as operatorforwarder from "./operatorforwarder";
export type { operatorforwarder };
import type * as shared from "./shared";
export type { shared };
import type * as vendor from "./vendor";
export type { vendor };
