/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as crossChainManagerSol from "./CrossChainManager.sol";
export type { crossChainManagerSol };
export type { DefiCraftDAO } from "./DefiCraftDAO";
export type { InstitutionalNFT } from "./InstitutionalNFT";
export type { Lock } from "./Lock";
export type { ResourceTracker } from "./ResourceTracker";
export type { Specialization } from "./Specialization";
export type { StakingAmulet } from "./StakingAmulet";
export type { TGEQuest } from "./TGEQuest";
export type { WorkshopFactory } from "./WorkshopFactory";
