/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IWorkshopFactory,
  IWorkshopFactoryInterface,
} from "../../../contracts/CrossChainManager.sol/IWorkshopFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IWorkshopFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IWorkshopFactoryInterface {
    return new Interface(_abi) as IWorkshopFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IWorkshopFactory {
    return new Contract(address, _abi, runner) as unknown as IWorkshopFactory;
  }
}
